name: Gitartwork from a contribution graph

on:
  push:

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jasineri/gitartwork@v1
        with:
          user_name: Shehroz  # Change this to your GitHub username
          text: SHEHROZ  # The text to display on Gitartwork
      - uses: jasineri/simple-push-action@v1

